"""add person_id and optimization_mode to optimization tables

Revision ID: 080ccd3b160a
Revises: 64a82453ad53
Create Date: 2026-03-24 19:14:27.797120
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '080ccd3b160a'
down_revision: Union[str, None] = '64a82453ad53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('optimization_jobs', sa.Column('person_id', sa.Uuid(), nullable=True))
    op.add_column('optimization_jobs', sa.Column('optimization_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('recommendations', sa.Column('optimization_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('recommendations', sa.Column('personal_brew_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'personal_brew_count')
    op.drop_column('recommendations', 'optimization_mode')
    op.drop_column('optimization_jobs', 'optimization_mode')
    op.drop_column('optimization_jobs', 'person_id')
    # ### end Alembic commands ###
