"""add optimization columns to brews

Revision ID: 0df4259bb556
Revises: afda093129ec
Create Date: 2026-03-23 17:59:39.453315
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0df4259bb556'
down_revision: Union[str, None] = 'afda093129ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brews', sa.Column('bloom_weight', sa.Float(), nullable=True))
    op.add_column('brews', sa.Column('preinfusion_pressure', sa.Float(), nullable=True))
    op.add_column('brews', sa.Column('pressure_profile', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('brews', sa.Column('brew_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('brews', sa.Column('saturation', sa.Float(), nullable=True))
    op.add_column('brews', sa.Column('bloom_pause', sa.Float(), nullable=True))
    op.add_column('brews', sa.Column('temp_profile', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brews', 'temp_profile')
    op.drop_column('brews', 'bloom_pause')
    op.drop_column('brews', 'saturation')
    op.drop_column('brews', 'brew_mode')
    op.drop_column('brews', 'pressure_profile')
    op.drop_column('brews', 'preinfusion_pressure')
    op.drop_column('brews', 'bloom_weight')
    # ### end Alembic commands ###
