"""remove grinder display_format column

Revision ID: afda093129ec
Revises: 06ff5ca210c4
Create Date: 2026-03-22 11:44:55.709023
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'afda093129ec'
down_revision: Union[str, None] = '06ff5ca210c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grinders', 'display_format')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grinders', sa.Column('display_format', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
