"""add_is_manual_to_measurements

Revision ID: c06d948aa2d7
Revises: e192b884d9c6
Create Date: 2026-02-22 21:00:21.125424

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c06d948aa2d7"
down_revision: Union[str, Sequence[str], None] = "e192b884d9c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("measurements", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_manual", sa.Boolean(), nullable=True, server_default=sa.text("0"))
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("measurements", schema=None) as batch_op:
        batch_op.drop_column("is_manual")

    # ### end Alembic commands ###
